### ISSUE TITLE
can't build

### ISSUE THREAD

**Issue by tivvit** [wyukawa/hadoop_exporter#6]
The Prometheus API probably changed

```
go build namenode_exporter.go
# command-line-arguments
./namenode_exporter.go:243: e.pnGcCount.Set undefined (type prometheus.Counter has no field or method Set)
./namenode_exporter.go:244: e.pnGcTime.Set undefined (type prometheus.Counter has no field or method Set)
./namenode_exporter.go:247: e.cmsGcCount.Set undefined (type prometheus.Counter has no field or method Set)
./namenode_exporter.go:248: e.cmsGcTime.Set undefined (type prometheus.Counter has no field or method Set)
```

**Comment by fnzv** [comment]
Same on Golang version 1.9.2  and i tried also with 1.6.2 on Ubuntu 16.04 LTS 
Probably this Prometheus client library is deprecated and/or updated.

**Comment by fnzv** [comment]
After i commented out the lines which are undefined and now you can compile it:
# go build namenode_exporter.go
# ./namenode_exporter 
INFO[0000] Starting Server: :9070

**Comment by wyukawa** [comment]
fixed in https://github.com/wyukawa/hadoop_exporter/pull/8
